language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra

script:
   - ./gradlew build test

branches:
  only:
  - master
  - dev
