language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra

jdk:
  - oraclejdk8

script:
   - ./gradlew build test jacocoTestReport generateRelease

after_success:
   - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
  - dev
