language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra

jdk:
  - oraclejdk8

script:
   - ./gradlew build test generateRelease

branches:
  only:
  - master
  - dev
