language: android

android:
  components:
    - tools
    - android-25
    - build-tools-25.0.3
    - platform-tools
    - extra

jdk:
  - oraclejdk8

script:
   - ./gradlew build test assembleRelease

after_success:
   - bash <(curl -s https://codecov.io/bash)

after_failure:
   - cat ./build/al-broco/bare-bones-digest/build/reports/lint-results.xml

branches:
  only:
  - master
  - dev
